project:
  type: website
  output-dir: docs

website:
  title: "Austin Martinez"
  favicon: Images/Logo_noback.png # change to logo
  navbar:
    title: false
    logo: Images/Logo_noback.png # change to logo
    logo-alt: "blah blah"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd # add your listing page file to your navbar
      - href: resources.qmd
        text: Resources
      - icon: github
        href: https://github.com/austinmartinez12/austinmartinez12.github.io
  page-footer: 
    left: Copyright 2025, Austin Martinez
    right:
     - icon: https://github.com/austinmartinez12
format:
  html:
    theme: style.scss
    toc: true
    page-layout: full
    mainfont: Nunito


